# Generated by Django 3.0.8 on 2020-07-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='note',
            new_name='newnote',
        ),
    ]
