# Generated by Django 3.0.8 on 2020-07-07 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20200707_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 7, 7, 20, 57, 14, 968323)),
            preserve_default=False,
        ),
    ]
